substitutions:
  device_name: oneplug1
  friendly_name: "OnePlug 1"
  device_description: "OnePlug wifi switch 1"
  main_icon: "power-socket-uk"
  # Options: `RESTORE_DEFAULT_OFF`, `RESTORE_DEFAULT_ON`, `ALWAYS_ON` & `ALWAYS_OFF`
  default_state: "RESTORE_DEFAULT_ON"
  # Number that the device will change from `Idle` to `Active` if power is greater than or equal to
  activity_threshold: "5"

## NOTE: POWER MONITORING IS BROKEN ON THIS PLUG, SO HAS BEEN REMOVED ##

esphome:
  name: $device_name
  friendly_name: $friendly_name

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.23.123.15
    gateway: 172.23.123.1
    subnet: 255.255.255.0
  ap:
    ssid: $device_name
    password: !secret hotspot_wifi_password
captive_portal:

web_server:
  port: 80
  include_internal: true

logger:
  level: INFO

api:
  encryption:
    key: !secret api_enc

ota:
  password: !secret ota_pwd

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/London

# Device Specific Config
binary_sensor:
  # Push Button (Toggles Relay When Pressed)
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Server Status"

switch:
  # Relay (As Switch)
  - platform: gpio
    name: "Switch"
    icon: "mdi:${main_icon}"
    pin: GPIO14
    id: relay
    restore_mode: "${default_state}"
    on_turn_on:
      - light.turn_on:
          id: led
          brightness: 100%
          transition_length: 0s
    on_turn_off:
      - light.turn_off:
          id: led
          transition_length: 0s

sensor:
  # WiFi Signal Sensor
  - platform: wifi_signal
    name: "WiFi Status"
    update_interval: 60s

# Relay State LED
output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  - platform: monochromatic
    output: state_led
    id: led

status_led:
  pin:
    number: GPIO13
    inverted: True
