substitutions:
  device_name: outside-bath
  friendly_name: "Outside temperature - Bath"

esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  framework: 
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.23.123.18
    gateway: 172.23.123.1
    subnet: 255.255.255.0
  ap:
    ssid: $device_name
    password: !secret hotspot_wifi_password
captive_portal:

web_server:
  port: 80
  include_internal: true

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_enc

ota:
  - platform: esphome
    password: !secret ota_pwd

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/London

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    address: 0xfa089ad4456c4828
    name: "Temperature"